# This file was *autogenerated* from the file mount_attack.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16); _sage_const_4 = Integer(4)
from scheme_oracle import KeyOracleRFC3526
from biquad_distinguisher import BiquadDistinguisher

if __name__ == "__main__":
    p = next_prime(_sage_const_2 **_sage_const_16 )
    while(p % _sage_const_4  != _sage_const_3 ):
        p = next_prime(p)

    no_of_queries = _sage_const_2 **_sage_const_16 
    
    my_oracle = KeyOracleRFC3526(p)
    my_distinguisher = BiquadDistinguisher(my_oracle)

    my_distinguisher.distinguish(no_of_queries)

    
    
